apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patchesStrategicMerge:
  - odh_model_controller_manager_patch.yaml
commonLabels:
  app.kubernetes.io/managed-by: odh-model-controller

configurations:
  - params.yaml
