---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./scripts/
  - ./quickstart.yaml
  - ./rbac/
  - ./manager

commonLabels:
  app.kubernetes.io/managed-by: modelmesh-controller

configurations:
  - params.yaml
